"Vundle Section Start
set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'Valloric/YouCompleteMe'
Plugin 'majutsushi/tagbar'
Plugin 'Lokaltog/vim-powerline'
Plugin 'Raimondi/delimitMate'
Plugin 'scrooloose/nerdcommenter'
" Plugin 'zxqfl/tabnine-vim'
" ADD YOUR PLUGIN
call vundle#end()
filetype plugin indent on
"Vundle Section End

" ------------ NERDTree config -------------
" " open a NERDTree automatically when vim starts up
" autocmd vimenter * NERDTree
" "open a NERDTree automatically when vim starts up if no files were specified
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
" "open NERDTree automatically when vim starts up on opening a directory
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 1 && isdirectory(argv()[0]) && !exists("s:std_in") | exe 'NERDTree' argv()[0] | wincmd p | ene | endif
" "map F2 to open NERDTree
map <F2> :NERDTreeToggle<CR>
" "close vim if the only window left open is a NERDTree
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
" ------------------------------------------

" --------------- YCM  ---------------------
let g:ycm_global_ycm_extra_conf = '$HOME/.vim/bundle/YouCompleteMe/third_party/ycmd/cpp/ycm/.ycm_extra_conf.py'
" ------------------------------------------

" -------------- delimitMate  --------------
let g:delimitMate_expand_cr = 1
" ------------------------------------------

" -------------- Tagbar --------------------
let g:tagbar_width=35
let g:tagbar_autofocus=1
let g:tagbar_left = 1
nmap <F4> :TagbarToggle<CR>
" ------------------------------------------

" -------------- vim-powerline -------------
let g:Powerline_symbols = 'fancy'
set encoding=utf-8 
set laststatus=2
" ------------------------------------------

" -------------- TabNine  --------------
" set rtp+=/Users/patrick_psq/.vim/bundle/tabnine-vim
" ------------------------------------------

syntax on

colorscheme desert

" Generated by VimConfig.com
" General
set number	" Show line numbers
set linebreak	" Break lines at word (requires Wrap lines)
" set showbreak=+++	" Wrap-broken line prefix
set textwidth=100	" Line wrap (number of cols)
set showmatch	" Highlight matching brace
set spell	" Enable spell-checking
set visualbell	" Use visual bell (no beeping)

set hlsearch	" Highlight all search results
set smartcase	" Enable smart-case search
set ignorecase	" Always case-insensitive
set incsearch	" Searches for strings incrementally

set autoindent	" Auto-indent new lines
set expandtab	" Use spaces instead of tabs
set shiftwidth=4	" Number of auto-indent spaces
set smartindent	" Enable smart-indent
set smarttab	" Enable smart-tabs
set softtabstop=4	" Number of spaces per Tab

" Advanced
set ruler	" Show row and column ruler information

set undolevels=1000	" Number of undo levels
set backspace=indent,eol,start	" Backspace behaviour

" cpp template
autocmd BufNewFile *.cc 0r ~/.vim/template/cpp_template.cc
autocmd BufNewFile *.cpp 0r ~/.vim/template/cpp_template.cc

" Run
nnoremap <F1>   <Esc>:w<CR>:!g++ -std=c++11 % -o /tmp/a.out && /tmp/a.out<CR>
" Compile
nnoremap <F3>   <Esc>:w<CR>:!g++ -std=c++11 %<CR>
" Debug
nnoremap <C-F1> <Esc>:w<CR>:!g++ -std=c++11 -g % -o /tmp/a.out && gdb /tmp/a.out<CR>
